package com.company.lndprotips.QuestionBank;

import com.company.lndprotips.QuestionModel.Question;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;

public class QuestionBank {

    // ----------> MATH
    // method to return math addition question list
    private static ArrayList<Question> mathAdditionQuestionList(){
        ArrayList<Question> questionList = new ArrayList<>();
        questionList.add(new Question("3 + 5 =", "2", "6", "8", "8", ""));
        questionList.add(new Question("3 + 1 =", "9", "7", "4", "4", ""));
        questionList.add(new Question("4 + 2 =", "6", "7", "9", "6", ""));
        questionList.add(new Question("4 + 3 =", "6", "7", "8", "7", ""));
        questionList.add(new Question("2 + 3 =", "3", "5", "7", "5", ""));
        questionList.add(new Question("2 + 2 =", "2", "3", "4", "4", ""));
        questionList.add(new Question("3 + 2 =", "3", "5", "7", "5", ""));
        questionList.add(new Question("4 + 4 =", "6", "7", "8", "8", ""));
        questionList.add(new Question("3 + 2 =", "4", "5", "8", "5", ""));
        questionList.add(new Question("4 + 5 =", "9", "7", "3", "9", ""));
        questionList.add(new Question("6 + 2 =", "4", "8", "3", "8", ""));
        questionList.add(new Question("5 + 5 =", "5", "7", "10", "10", ""));
        questionList.add(new Question("6 + 3 =", "7", "9", "3", "9", ""));
        questionList.add(new Question("5 + 7 =", "9", "11", "12", "12", ""));
        questionList.add(new Question("9 + 4 =", "17", "13", "11", "13", ""));
        questionList.add(new Question("11 + 3 =", "14", "17", "11", "14", ""));
        questionList.add(new Question("13 + 5 =", "15", "18", "13", "18", ""));
        questionList.add(new Question("10 + 8 =", "18", "13", "19", "18", ""));
        questionList.add(new Question("10 + 3 =", "11", "17", "13", "13", ""));
        questionList.add(new Question("11 + 5 =", "19", "13", "16", "16", ""));
        questionList.add(new Question("15 + 2 =", "17", "21", "29", "17", ""));
        questionList.add(new Question("11 + 6 =", "29", "17", "11", "17", ""));
        questionList.add(new Question("18 + 1 =", "21", "19", "23", "19", ""));
        questionList.add(new Question("18 + 2 =", "20", "22", "29", "20", ""));
        questionList.add(new Question("14 + 2 =", "19", "17", "16", "16", ""));
        questionList.add(new Question("11 + 3 =", "17", "15", "14", "14", ""));
        questionList.add(new Question("10 + 5 =", "11", "13", "15", "15", ""));
        questionList.add(new Question("16 + 3 =", "19", "17", "15", "19", ""));
        questionList.add(new Question("20 + 6 =", "21", "26", "29", "26", ""));
        questionList.add(new Question("15 + 4 =", "17", "18", "19", "19", ""));
        questionList.add(new Question("11 + 5 =", "12", "13", "16", "16", ""));
        questionList.add(new Question("18 + 2 =", "20", "23", "25", "20", ""));
        questionList.add(new Question("11 + 6 =", "21", "17", "13", "17", ""));
        questionList.add(new Question("15 + 3 =", "17", "18", "21", "18", ""));
        questionList.add(new Question("20 + 4 =", "28", "24", "31", "24", ""));
        questionList.add(new Question("21 + 7 =", "21", "25", "28", "28", ""));
        questionList.add(new Question("18 + 6 =", "24", "34", "44", "24", ""));
        questionList.add(new Question("15 + 9 =", "24", "36", "44", "24", ""));
        questionList.add(new Question("16 + 6 =", "21", "27", "22", "22", ""));
        questionList.add(new Question("13 + 7 =", "17", "19", "20", "20", ""));
        questionList.add(new Question("50 + 30 =", "70", "80", "90", "80", ""));
        questionList.add(new Question("90 + 70 =", "118", "150", "160", "160", ""));
        questionList.add(new Question("90 + 20 =", "110", "120", "130", "110", ""));
        questionList.add(new Question("80 + 50 =", "110", "130", "140", "130", ""));
        questionList.add(new Question("90 + 80 =", "160", "170", "180", "170", ""));
        questionList.add(new Question("49 + 10 =", "59", "69", "79", "79", ""));
        questionList.add(new Question("40 + 20 =", "50", "60", "70", "60", ""));
        questionList.add(new Question("26 + 30 =", "53", "54", "56", "56", ""));
        questionList.add(new Question("32 + 40 =", "72", "89", "52", "72", ""));
        questionList.add(new Question("37 + 50 =", "67", "79", "87", "87", ""));
        questionList.add(new Question("48 + 10 =", "51", "58", "68", "58", ""));
        questionList.add(new Question("45 + 30 =", "55", "75", "59", "75", ""));
        questionList.add(new Question("71 + 30 =", "101", "105", "111", "101", ""));
        questionList.add(new Question("62 + 50 =", "112", "122", "142", "112", ""));
        questionList.add(new Question("32 + 73 =", "120", "105", "135", "105", ""));
        questionList.add(new Question("12 + 78 =", "90", "100", "80", "90", ""));
        questionList.add(new Question("54 + 12 =", "60", "63", "66", "66", ""));
        questionList.add(new Question("90 + 12 =", "120", "108", "102", "102", ""));
        questionList.add(new Question("64 + 23 =", "77", "83", "87", "87", ""));
        questionList.add(new Question("76 + 52 =", "128", "129", "133", "128", ""));
        questionList.add(new Question("12 + 2 + 1 =", "11", "13", "15", "15", ""));
        questionList.add(new Question("10 + 4 + 1 =", "11", "13", "15", "15", ""));
        questionList.add(new Question("14 + 2 + 1 =", "17", "19", "21", "17", ""));
        questionList.add(new Question("12 + 2 + 2 =", "11", "13", "16", "16", ""));
        questionList.add(new Question("10 + 7 + 3 =", "17", "12", "20", "20", ""));
        questionList.add(new Question("55 + 3 + 1 =", "59", "51", "69", "59", ""));
        questionList.add(new Question("35 + 2 + 7 =", "41", "44", "33", "44", ""));
        questionList.add(new Question("25 + 5 + 9 =", "33", "35", "39", "39", ""));
        questionList.add(new Question("11 + 7 + 0 =", "13", "18", "23", "18", ""));
        questionList.add(new Question("14 + 9 + 6 =", "29", "33", "39", "29", ""));
        questionList.add(new Question("17 + 2 + 1 =", "16", "19", "20", "20", ""));
        questionList.add(new Question("19 + 1 + 3 =", "18", "23", "28", "23", ""));
        questionList.add(new Question("13 + 3 + 5 =", "16", "19", "21", "21", ""));
        questionList.add(new Question("11 + 5 + 7 =", "23", "27", "31", "23", ""));
        questionList.add(new Question("17 + 9 + 0 =", "21", "23", "26", "26", ""));
        return questionList;
    }

    // method to return math subtraction question list
    private static ArrayList<Question> mathSubtractionQuestionList(){
        ArrayList<Question> questionList = new ArrayList<>();
        questionList.add(new Question("4 - 2 =", "1", "2", "3", "2", ""));
        questionList.add(new Question("7 - 3 =", "5", "3", "4", "4", ""));
        questionList.add(new Question("5 - 4 =", "3", "1", "5", "1", ""));
        questionList.add(new Question("7 – 3 =", "2", "3", "4", "4", ""));
        questionList.add(new Question("9 – 3 =", "5", "6", "7", "6", ""));
        questionList.add(new Question("7 – 2 =", "2", "4", "5", "5", ""));
        questionList.add(new Question("5 – 4 =", "1", "2", "3", "1", ""));
        questionList.add(new Question("9 – 2 =", "5", "7", "8", "7", ""));
        questionList.add(new Question("5 – 3 =", "1", "2", "3", "2", ""));
        questionList.add(new Question("8 – 2 =", "4", "5", "6", "6", ""));
        questionList.add(new Question("6 – 3 =", "2", "3", "4", "3", ""));
        questionList.add(new Question("8 – 1 =", "3", "5", "7", "7", ""));
        questionList.add(new Question("12 - 3 =", "3", "9", "7", "9", ""));
        questionList.add(new Question("11 - 5 =", "4", "5", "6", "6", ""));
        questionList.add(new Question("14 - 4 =", "11", "13", "10", "10", ""));
        questionList.add(new Question("19 - 7 =", "10", "12", "11", "12", ""));
        questionList.add(new Question("13 - 8 =", "1", "4", "5", "5", ""));
        questionList.add(new Question("24 - 9 =", "12", "15", "19", "15", ""));
        questionList.add(new Question("10 – 5 =", "4", "5", "7", "5", ""));
        questionList.add(new Question("10 – 2 =", "4", "6", "8", "8", ""));
        questionList.add(new Question("14 – 5 =", "9", "6", "3", "9", ""));
        questionList.add(new Question("13 – 2 =", "10", "11", "12", "11", ""));
        questionList.add(new Question("11 – 5 =", "4", "5", "6", "6", ""));
        questionList.add(new Question("19 – 4 =", "15", "17", "19", "15", ""));
        questionList.add(new Question("21 - 15 =", "1", "2", "3", "6", ""));
        questionList.add(new Question("60 – 10 =", "20", "35", "50", "50", ""));
        questionList.add(new Question("90 – 30 =", "40", "50", "60", "60", ""));
        questionList.add(new Question("80 – 60 =", "10", "20", "30", "20", ""));
        questionList.add(new Question("45 – 20 =", "20", "25", "30", "25", ""));
        questionList.add(new Question("48 – 40 =", "4", "6", "8", "8", ""));
        questionList.add(new Question("34 – 10 =", "20", "24", "28", "24", ""));
        questionList.add(new Question("39 – 30 =", "9", "3", "6", "9", ""));
        questionList.add(new Question("96 – 80 =", "13", "16", "19", "16", ""));
        questionList.add(new Question("70 – 20 =", "30", "40", "50", "50", ""));
        questionList.add(new Question("70 – 30 =", "30", "40", "50", "40", ""));
        questionList.add(new Question("90 – 80 =", "10", "20", "30", "10", ""));
        questionList.add(new Question("22 – 10 =", "11", "12", "22", "12", ""));
        questionList.add(new Question("47 – 30 =", "15", "16", "17", "17", ""));
        questionList.add(new Question("41 – 40 =", "1", "1", "2", "1", ""));
        questionList.add(new Question("82 – 60 =", "21", "22", "23", "22", ""));
        questionList.add(new Question("69 - 54 =", "13", "14", "15", "15", ""));
        questionList.add(new Question("80 - 55 =", "15", "25", "35", "25", ""));
        questionList.add(new Question("70 - 50 =", "10", "20", "30", "20", ""));
        questionList.add(new Question("70 - 35 =", "15", "25", "35", "35", ""));
        questionList.add(new Question("30 - 10 =", "20", "30", "40", "20", ""));
        questionList.add(new Question("80 - 60 =", "40", "30", "20", "20", ""));
        questionList.add(new Question("80 - 30 =", "50", "20", "40", "50", ""));
        questionList.add(new Question("30 - 20 =", "10", "15", "30", "10", ""));
        questionList.add(new Question("70 - 20 =", "30", "40", "50", "50", ""));
        questionList.add(new Question("70 - 30 =", "30", "40", "50", "40", ""));
        questionList.add(new Question("90 - 40 =", "50", "20", "30", "50", ""));
        questionList.add(new Question("40 - 30 =", "10", "20", "30", "10", ""));
        questionList.add(new Question("90 - 30 =", "40", "50", "60", "60", ""));
        questionList.add(new Question("80 - 40 =", "30", "40", "50", "40", ""));
        questionList.add(new Question("90 - 20 =", "50", "60", "70", "70", ""));
        questionList.add(new Question("90 - 90 =", "0", "1", "2", "0", ""));
        questionList.add(new Question("90 - 40 =", "30", "40", "50", "50", ""));
        questionList.add(new Question("70 - 30 =", "30", "40", "50", "40", ""));
        questionList.add(new Question("425 – 10 =", "415", "405", "435", "415", ""));
        questionList.add(new Question("431 – 10 =", "411", "401", "421", "421", ""));
        questionList.add(new Question("527 – 10 =", "507", "527", "517", "517", ""));
        questionList.add(new Question("635 – 10 =", "635", "625", "615", "625", ""));
        questionList.add(new Question("724 – 10 =", "704", "724", "714", "714", ""));
        questionList.add(new Question("295 – 10 =", "285", "275", "295", "285", ""));
        questionList.add(new Question("575 – 10 =", "565", "555", "575", "565", ""));
        questionList.add(new Question("816 – 10 =", "826", "836", "806", "806", ""));
        questionList.add(new Question("386 – 10 =", "356", "376", "366", "376", ""));
        questionList.add(new Question("448 – 10 =", "438", "418", "428", "438", ""));
        questionList.add(new Question("860 - 20 =", "850", "830", "840", "840", ""));
        questionList.add(new Question("210 - 10 =", "220", "200", "230", "200", ""));
        questionList.add(new Question("910 - 10 =", "900", "910", "920", "900", ""));
        questionList.add(new Question("280 - 50 =", "230", "210", "220", "230", ""));
        questionList.add(new Question("730 - 20 =", "720", "710", "700", "710", ""));
        questionList.add(new Question("750 - 40 =", "730", "720", "710", "710", ""));
        questionList.add(new Question("590 - 80 =", "500", "510", "580", "510", ""));
        return questionList;
    }

    // method to return math multiplication question list
    private static ArrayList<Question> mathMultiplicationQuestionList(){
        ArrayList<Question> questionList = new ArrayList<>();
        questionList.add(new Question("3 × 2 =", "2", "5", "6", "6", ""));
        questionList.add(new Question("2 × 2 =", "3", "4", "6", "4", ""));
        questionList.add(new Question("6 × 2 =", "10", "14", "12", "12", ""));
        questionList.add(new Question("8 × 2 =", "16", "12", "18", "16", ""));
        questionList.add(new Question("10 × 2 =", "20", "10", "30", "20", ""));
        questionList.add(new Question("7 × 2 =", "16", "14", "12", "14", ""));
        questionList.add(new Question("9 × 2 =", "18", "16", "20", "18", ""));
        questionList.add(new Question("4 × 2 =", "10", "6", "8", "8", ""));
        questionList.add(new Question("10 × 3 =", "30", "20", "40", "30", ""));
        questionList.add(new Question("7 × 3 =", "24", "21", "19", "21", ""));
        questionList.add(new Question("9 × 3 =", "24", "28", "27", "27", ""));
        questionList.add(new Question("3 × 3 =", "9", "12", "6", "9", ""));
        questionList.add(new Question("4 × 3 =", "8", "14", "12", "12", ""));
        questionList.add(new Question("2 × 3 =", "6", "8", "4", "6", ""));
        questionList.add(new Question("6 × 3 =", "16", "18", "21", "18", ""));
        questionList.add(new Question("8 × 3 =", "24", "27", "22", "24", ""));
        questionList.add(new Question("8 × 4 =", "22", "32", "42", "32", ""));
        questionList.add(new Question("2 × 4 =", "6", "10", "8", "8", ""));
        questionList.add(new Question("7 × 4 =", "24", "28", "32", "28", ""));
        questionList.add(new Question("4 × 4 =", "14", "12", "16", "16", ""));
        questionList.add(new Question("3 × 4 =", "12", "15", "18", "12", ""));
        questionList.add(new Question("5 × 4 =", "15", "20", "25", "20", ""));
        questionList.add(new Question("10 × 4 =", "40", "30", "50", "40", ""));
        questionList.add(new Question("6 × 4 =", "30", "24", "20", "24", ""));
        questionList.add(new Question("5 × 5 =", "30", "15", "25", "25", ""));
        questionList.add(new Question("10 × 5 =", "50", "40", "60", "50", ""));
        questionList.add(new Question("4 × 5 =", "25", "20", "15", "20", ""));
        questionList.add(new Question("2 × 5 =", "10", "8", "12", "10", ""));
        questionList.add(new Question("3 × 5 =", "15", "12", "18", "15", ""));
        questionList.add(new Question("8 × 5 =", "32", "40", "48", "40", ""));
        questionList.add(new Question("7 × 5 =", "35", "28", "42", "35", ""));
        questionList.add(new Question("6 × 5 =", "24", "30", "36", "30", ""));
        questionList.add(new Question("5 × 10 =", "50", "40", "60", "50", ""));
        questionList.add(new Question("7 × 10 =", "60", "70", "80", "70", ""));
        questionList.add(new Question("8 × 10 =", "70", "90", "80", "80", ""));
        questionList.add(new Question("6 × 10 =", "60", "50", "70", "60", ""));
        questionList.add(new Question("3 × 10 =", "20", "30", "40", "30", ""));
        questionList.add(new Question("9 × 10 =", "80", "70", "90", "90", ""));
        questionList.add(new Question("4 × 10 =", "40", "30", "40", "40", ""));
        questionList.add(new Question("2 × 10 =", "40", "30", "20", "20", ""));
        questionList.add(new Question("1 x 1 =", "1", "0", "2", "1", ""));
        questionList.add(new Question("1 x 2 =", "4", "2", "1", "2", ""));
        questionList.add(new Question("1 x 3 =", "1", "2", "3", "3", ""));
        questionList.add(new Question("1 x 4 =", "4", "0", "6", "4", ""));
        questionList.add(new Question("1 x 5 =", "5", "10", "0", "5", ""));
        questionList.add(new Question("1 x 6 =", "3", "6", "4", "6", ""));
        questionList.add(new Question("1 x 7 =", "7", "1", "5", "7", ""));
        questionList.add(new Question("1 x 8 =", "18", "7", "8", "8", ""));
        questionList.add(new Question("1 x 9 =", "9", "8", "10", "9", ""));
        questionList.add(new Question("1 x 10 =", "10", "1", "20", "10", ""));
        questionList.add(new Question("1 x 11 =", "12", "11", "22", "11", ""));
        questionList.add(new Question("1 x 12 =", "0", "24", "12", "12", ""));
        questionList.add(new Question("2 x 1 =", "1", "2", "3", "2", ""));
        questionList.add(new Question("2 x 2 =", "4", "2", "6", "4", ""));
        questionList.add(new Question("2 x 3 =", "6", "8", "9", "6", ""));
        questionList.add(new Question("2 x 4 =", "12", "8", "4", "8", ""));
        questionList.add(new Question("2 x 5 =", "10", "5", "15", "10", ""));
        questionList.add(new Question("2 x 6 =", "13", "12", "14", "12", ""));
        questionList.add(new Question("2 x 7 =", "14", "21", "15", "14", ""));
        questionList.add(new Question("2 x 8 =", "12", "24", "16", "16", ""));
        questionList.add(new Question("2 x 9 =", "21", "18", "19", "18", ""));
        questionList.add(new Question("2 x 10 =", "20", "10", "30", "20", ""));
        questionList.add(new Question("3 x 1 =", "3", "0", "6", "3", ""));
        questionList.add(new Question("2 x 12 =", "21", "23", "24", "24", ""));
        questionList.add(new Question("2 x 11 =", "32", "33", "22", "22", ""));
        return questionList;
    }

    // method to return math division question list
    private static ArrayList<Question> mathDivisionQuestionList(){
        ArrayList<Question> questionList = new ArrayList<>();
        questionList.add(new Question("5 ÷ 5 =", "0", "1", "2", "1", ""));
        questionList.add(new Question("3 ÷ 3 =", "1", "0", "3", "1", ""));
        questionList.add(new Question("63 ÷ 9 =", "8", "7", "6", "7", ""));
        questionList.add(new Question("30 ÷ 6 =", "5", "4", "6", "5", ""));
        questionList.add(new Question("33 ÷ 3 =", "12", "11", "13", "11", ""));
        questionList.add(new Question("32 ÷ 4 =", "7", "9", "8", "8", ""));
        questionList.add(new Question("36 ÷ 4 =", "9", "8", "6", "9", ""));
        questionList.add(new Question("48 ÷ 6 =", "9", "7", "8", "8", ""));
        questionList.add(new Question("35 ÷ 7 =", "4", "6", "5", "5", ""));
        questionList.add(new Question("27 ÷ 9 =", "3", "4", "6", "3", ""));
        questionList.add(new Question("6 ÷ 3 =", "3", "6", "2", "2", ""));
        questionList.add(new Question("24 ÷ 2 =", "13", "12", "14", "12", ""));
        questionList.add(new Question("50 ÷ 10 =", "5", "4", "6", "5", ""));
        questionList.add(new Question("30 ÷ 10 =", "5", "4", "3", "3", ""));
        questionList.add(new Question("20 ÷ 5 =", "4", "5", "3", "4", ""));
        questionList.add(new Question("16 ÷ 4 =", "5", "6", "4", "4", ""));
        questionList.add(new Question("9 ÷ 3 =", "3", "4", "2", "3", ""));
        questionList.add(new Question("96 ÷ 8 =", "14", "15", "12", "12", ""));
        questionList.add(new Question("32 ÷ 8 =", "4", "5", "6", "4", ""));
        questionList.add(new Question("24 ÷ 6 =", "5", "6", "4", "4", ""));
        questionList.add(new Question("3 ÷ 3 =", "1", "0", "3", "1", ""));
        questionList.add(new Question("63 ÷ 9 =", "6", "7", "8", "7", ""));
        questionList.add(new Question("20 ÷ 4 =", "4", "6", "5", "5", ""));
        questionList.add(new Question("81 ÷ 9 =", "9", "8", "6", "9", ""));
        questionList.add(new Question("48 ÷ 4 =", "14", "12", "13", "12", ""));
        questionList.add(new Question("54 ÷ 6 =", "9", "5", "7", "9", ""));
        questionList.add(new Question("60 ÷ 12 =", "7", "5", "8", "5", ""));
        questionList.add(new Question("18 ÷ 9 =", "2", "3", "1", "2", ""));
        questionList.add(new Question("24 ÷ 8 =", "4", "6", "3", "3", ""));
        questionList.add(new Question("50 ÷ 5 =", "10", "9", "5", "10", ""));
        questionList.add(new Question("90 ÷ 9 =", "12", "9", "10", "10", ""));
        questionList.add(new Question("70 ÷ 7 =", "10", "5", "9", "10", ""));
        questionList.add(new Question("45 ÷ 9 =", "9", "7", "5", "5", ""));
        questionList.add(new Question("15 ÷ 5 =", "3", "2", "4", "3", ""));
        questionList.add(new Question("72 ÷ 9 =", "6", "9", "8", "8", ""));
        questionList.add(new Question("18 ÷ 6 =", "3", "6", "4", "3", ""));
        questionList.add(new Question("16 ÷ 4 =", "6", "5", "4", "4", ""));
        questionList.add(new Question("48 ÷ 6 =", "8", "7", "9", "8", ""));
        questionList.add(new Question("30 ÷ 10 =", "3", "4", "2", "3", ""));
        questionList.add(new Question("56 ÷ 7 =", "9", "7", "8", "8", ""));
        questionList.add(new Question("36 ÷ 6 =", "6", "5", "7", "6", ""));
        questionList.add(new Question("70 ÷ 7 =", "8", "9", "10", "10", ""));
        questionList.add(new Question("4 ÷ 4 =", "1", "0", "4", "1", ""));
        questionList.add(new Question("55 ÷ 5 =", "12", "10", "11", "11", ""));
        questionList.add(new Question("24 ÷ 8 =", "3", "4", "8", "3", ""));
        questionList.add(new Question("21 ÷ 7 =", "5", "7", "3", "3", ""));
        questionList.add(new Question("28 ÷ 7 =", "3", "4", "5", "4", ""));
        questionList.add(new Question("21 ÷ 3 =", "7", "6", "8", "7", ""));
        questionList.add(new Question("50 ÷ 10 =", "4", "7", "5", "5", ""));
        questionList.add(new Question("54 ÷ 6 =", "9", "8", "5", "9", ""));
        questionList.add(new Question("40 ÷ 8 =", "7", "8", "5", "5", ""));
        questionList.add(new Question("72 ÷ 8 =", "7", "9", "8", "9", ""));
        questionList.add(new Question("12 ÷ 3 =", "4", "6", "5", "4", ""));
        questionList.add(new Question("32 ÷ 4 =", "8", "7", "9", "8", ""));
        questionList.add(new Question("99 ÷ 11 =", "9", "8", "10", "9", ""));
        questionList.add(new Question("56 ÷ 7 =", "6", "9", "8", "8", ""));
        questionList.add(new Question("36 ÷ 3 =", "12", "14", "3", "12", ""));
        questionList.add(new Question("30 ÷ 3 =", "9", "11", "10", "10", ""));
        questionList.add(new Question("96 ÷ 8 =", "11", "16", "12", "12", ""));
        questionList.add(new Question("16 ÷ 2 =", "8", "6", "9", "8", ""));
        questionList.add(new Question("5 ÷ 5 =", "0", "1", "5", "1", ""));
        questionList.add(new Question("8 ÷ 4 =", "2", "1", "4", "2", ""));
        questionList.add(new Question("21 ÷ 7 =", "3", "4", "7", "3", ""));
        questionList.add(new Question("6 ÷ 1 =", "1", "0", "6", "6", ""));
        questionList.add(new Question("30 ÷ 10 =", "3", "2", "4", "3", ""));
        questionList.add(new Question("25 ÷ 5 =", "6", "7", "5", "5", ""));
        questionList.add(new Question("16 ÷ 4 =", "4", "8", "6", "4", ""));
        questionList.add(new Question("6 ÷ 6 =", "0", "2", "1", "1", ""));
        questionList.add(new Question("40 ÷ 4 =", "10", "12", "9", "10", ""));
        questionList.add(new Question("33 ÷ 3 =", "11", "13", "17", "11", ""));
        questionList.add(new Question("81 ÷ 9 =", "5", "8", "9", "9", ""));
        questionList.add(new Question("55 ÷ 5 =", "11", "12", "13", "11", ""));
        questionList.add(new Question("45 ÷ 5 =", "8", "7", "9", "9", ""));
        questionList.add(new Question("60 ÷ 5 =", "14", "10", "12", "12", ""));
        questionList.add(new Question("36 ÷ 6 =", "6", "7", "8", "6", ""));
        questionList.add(new Question("60 ÷ 6 =", "9", "10", "8", "10", ""));
        questionList.add(new Question("50 ÷ 5 =", "10", "11", "9", "10", ""));
        questionList.add(new Question("18 ÷ 6 =", "5", "6", "3", "3", ""));
        questionList.add(new Question("55 ÷ 5 =", "11", "10", "12", "11", ""));
        questionList.add(new Question("1 ÷ 1 =", "0", "1", "2", "1", ""));
        return questionList;
    }

    // ----------> ENGLISH
    // method to return english Is Am Are question list
    private static ArrayList<Question> englishIsAmAreQuestionList(){
        ArrayList<Question> questionList = new ArrayList<>();
        questionList.add(new Question("It ____ easy.", "is", "am", "are", "is", ""));
        questionList.add(new Question("There ____ some people waiting to see you.", "is", "am", "are", "are", ""));
        questionList.add(new Question("There ____ some money to pay into the bank.", "is", "am", "is", "", ""));
        questionList.add(new Question("They ____ coming.", "is", "am", "are", "are", ""));
        questionList.add(new Question("We ____ nearly ready.", "is", "am", "are", "are", ""));
        questionList.add(new Question("It ____ impossible.", "is", "am", "are", "is", ""));
        questionList.add(new Question("He ____ unfriendly.", "is", "am", "are", "is", ""));
        questionList.add(new Question("You ____ not to blame.", "is", "am", "are", "are", ""));
        questionList.add(new Question("How much ____ it?", "is", "am", "are", "is", ""));
        questionList.add(new Question("Who ____ on the phone?", "is", "am", "are", "is", ""));
        questionList.add(new Question("Each week ____ worse.", "is", "am", "are", "is", ""));
        questionList.add(new Question("Everybody ____ leaving now.", "is", "am", "are", "is", ""));
        questionList.add(new Question("____ anybody there?", "is", "am", "are", "is", ""));
        questionList.add(new Question("Whose ____ those books?", "is", "am", "are", "are", ""));
        questionList.add(new Question("I ____ feeling very tired.", "is", "am", "are", "am", ""));
        questionList.add(new Question("I ____ happy right now.", "is", "am", "are", "am", ""));
        questionList.add(new Question("She ____ hungry.", "is", "am", "are", "is", ""));
        questionList.add(new Question("It ____ cold.", "is", "am", "are", "is", ""));
        questionList.add(new Question("We ____ walking.", "is", "am", "are", "are", ""));
        questionList.add(new Question("They ____ swimming.", "is", "am", "are", "are", ""));
        questionList.add(new Question("Ali ____ in the house.", "is", "am", "are", "is", ""));
        questionList.add(new Question("The cat ____ in the garden.", "is", "am", "are", "is", ""));
        questionList.add(new Question("The woman ____ laughing.", "is", "am", "are", "is", ""));
        questionList.add(new Question("Peter ____ a clever boy.", "is", "am", "are", "is", ""));
        questionList.add(new Question("It ____ time for dinner.", "is", "am", "are", "is", ""));
        questionList.add(new Question("My name ____ Siti.", "is", "am", "are", "is", ""));
        questionList.add(new Question("My rabbit ____ white.", "is", "am", "are", "is", ""));
        questionList.add(new Question("They ____ very happy.", "is", "am", "are", "are", ""));
        questionList.add(new Question("The children ____ eating.", "is", "am", "are", "are", ""));
        questionList.add(new Question("He ____ a teacher.", "is", "am", "are", "", "is"));
        questionList.add(new Question("Ali ____ a tall boy", "is", "am", "are", "", "is"));
        questionList.add(new Question("I ____ ten years old.", "is", "am", "are", "", "am"));
        questionList.add(new Question("I ____ not tired.", "is", "am", "are", "", "am"));
        questionList.add(new Question("He ____ happy.", "is", "am", "are", "is", ""));
        questionList.add(new Question("You ____ clever.", "is", "am", "are", "are", ""));
        questionList.add(new Question("I ____ late.", "is", "am", "are", "am", ""));
        questionList.add(new Question("She ____ a clever girl.", "is", "am", "are", "is", ""));
        questionList.add(new Question("David ____ feeding his fish.", "is", "am", "are", "is", ""));
        questionList.add(new Question("I ____ very hungry.", "is", "am", "are", "am", ""));
        questionList.add(new Question("We ____ the champions.", "is", "am", "are", "are", ""));
        questionList.add(new Question("It ____ a bulldog.", "is", "am", "are", "is", ""));
        questionList.add(new Question("The boy ____ crying.", "is", "am", "are", "is", ""));
        questionList.add(new Question("You ____ watching TV.", "is", "am", "are", "are", ""));
        questionList.add(new Question("It ____ running away.", "is", "am", "are", "is", ""));
        questionList.add(new Question("He ____ singing a song.", "is", "am", "are", "is", ""));
        questionList.add(new Question("Mrs Raju ____ a teacher.", "is", "am", "are", "is", ""));
        questionList.add(new Question("I ____ an artist.", "is", "am", "are", "am", ""));
        questionList.add(new Question("I ____ riding a bicycle.", "is", "am", "are", "am", ""));
        questionList.add(new Question("Anna ____ talking to the teacher.", "is", "am", "are", "is", ""));
        questionList.add(new Question("Mary ____ sitting on a chair.", "is", "am", "are", "is", ""));
        questionList.add(new Question("We ____ going to play football.", "is", "am", "are", "are", ""));
        questionList.add(new Question("You ____ going home.", "is", "am", "are", "are", ""));
        questionList.add(new Question("Tom ____ a student.", "is", "am", "are", "is", ""));
        questionList.add(new Question("We ____ reading.", "is", "am", "are", "are", ""));
        questionList.add(new Question("I ____ climbing a tree.", "is", "am", "are", "am", ""));
        questionList.add(new Question("She ____ my best friend.", "is", "am", "are", "is", ""));
        questionList.add(new Question("He ____ writing a letter.", "is", "am", "are", "is", ""));
        questionList.add(new Question("Mother ____ cooking dinner.", "is", "am", "are", "is", ""));
        questionList.add(new Question("Father ____ working in the garage.", "is", "am", "are", "is", ""));
        questionList.add(new Question("It ____ a dog.", "is", "am", "are", "", "is"));
        questionList.add(new Question("You ____ wonderful.", "is", "am", "are", "are", ""));
        questionList.add(new Question("They ____ waiting for us.", "is", "am", "are", "are", ""));
        questionList.add(new Question("We ____ preparing for the test.", "is", "am", "are", "are", ""));
        questionList.add(new Question("Boys ____ playing in the garden.", "is", "am", "are", "are", ""));
        questionList.add(new Question("I ____ working on my computer.", "is", "am", "are", "am", ""));
        questionList.add(new Question("My sister ____ a nurse.", "is", "am", "are", "is", ""));
        questionList.add(new Question("She ____ working on her computer.", "is", "am", "are", "is", ""));
        questionList.add(new Question("It ____ an elephant.", "is", "am", "are", "", "is"));
        questionList.add(new Question("Birds ____ flying in the sky.", "is", "am", "are", "are", ""));
        questionList.add(new Question("The baby ____ sleeping.", "is", "am", "are", "is", ""));
        questionList.add(new Question("The girls ____ singing devotional songs.", "is", "am", "are", "are", ""));
        questionList.add(new Question("____ you coming with me?", "is", "am", "are", "are", ""));
        questionList.add(new Question("____ they ready yet?", "is", "am", "are", "are", ""));
        questionList.add(new Question("Where ____ the books?", "is", "am", "are", "are", ""));
        questionList.add(new Question("Where ____ my pen?", "is", "am", "are", "is", ""));
        questionList.add(new Question("What ____ this?", "is", "am", "are", "is", ""));
        return questionList;
    }

    // method to return english punctuation question list
    private static ArrayList<Question> englishPunctuationList(){
        ArrayList<Question> questionList = new ArrayList<>();
        questionList.add(new Question("She ___ well at sports.", "", "", "", "Does",""));
        questionList.add(new Question("Jam and I are friends. ___ like to play together.", "", "", "", "We",""));
        questionList.add(new Question("We ___ not have class today.", "", "", "", "Do",""));
        questionList.add(new Question("The balls ___ new.", "", "", "", "Are",""));
        questionList.add(new Question("She ___ my friend.", "", "", "", "Is",""));
        questionList.add(new Question("Those ____ beautiful shoes.", "", "", "", "Are",""));
        questionList.add(new Question("Do you ____ two pencils?", "", "", "", "Have",""));
        questionList.add(new Question("I ___ a new pen.", "", "", "", "Have",""));
        questionList.add(new Question("My name is Sam. __ am 7 years old.", "", "", "", "I",""));
        questionList.add(new Question("My favorite fruit ___ apple.", "", "", "", "Is",""));
        questionList.add(new Question("She ____ a new bag.", "", "", "", "Has",""));
        questionList.add(new Question("Birds ____  wings.", "", "", "", "Have",""));
        questionList.add(new Question("Shar and Lene are grade 1 pupils. ____ are my good friends.", "", "", "", "They",""));
        questionList.add(new Question("I ___ good at climbing trees.", "", "", "", "Am",""));
        questionList.add(new Question("I have to ___ my homework.", "", "", "", "Do",""));
        questionList.add(new Question("They ___ at the zoo.", "", "", "", "Are",""));
        questionList.add(new Question("Jo and Mark ___ not want to go.", "", "", "", "Do",""));
        questionList.add(new Question("I have a sister. ___ is 10 years old.", "", "", "", "She",""));
        questionList.add(new Question("My father is 37 years old. ___ is so kind and loving.", "", "", "", "He",""));
        questionList.add(new Question("Sonny and Baek  ___  eating ice cream.", "", "", "", "Are",""));
        questionList.add(new Question("I like your new shoes", "", "", "", ".",""));
        questionList.add(new Question("Ouch, that hurt a lot", "", "", "", "!",""));
        questionList.add(new Question("No way, that is awesome", "", "", "", "!",""));
        questionList.add(new Question("Where is my notebook", "", "", "", "?",""));
        questionList.add(new Question("Can you repeat the question", "", "", "", "?",""));
        questionList.add(new Question("I'm going to the grocery store", "", "", "", ".",""));
        questionList.add(new Question("Please be patient", "", "", "", ".",""));
        questionList.add(new Question("Hey, get back here NOW", "", "", "", "!",""));
        questionList.add(new Question("Do you want another one", "", "", "", "?",""));
        questionList.add(new Question("Peter... Liza... and Amanda will decide.", "", "", "", ", comma",""));
        questionList.add(new Question("When will you come back to our city....", "", "", "", "? question mark",""));
        questionList.add(new Question("Wow.... You really got the highest marks in the class.", "", "", "", "! exclamation mark",""));
        questionList.add(new Question("hey offered the students bananas... oranges... and grapes.", "", "", "", ", a comma",""));
        questionList.add(new Question("My cousin considers himself a self...made man.", "", "", "", "- hyphen",""));
        questionList.add(new Question("...I haven't eaten anything today,... said Tom.", "", "", "", "\" \" speech marks",""));
        questionList.add(new Question("The students were advised to use the following items... a pencil, a ruler, and a notebook.", "", "", "", ": a colon",""));
        questionList.add(new Question("Sam... the mechanic... fixed the car.", "", "", "", ", comma",""));
        questionList.add(new Question("Amanda lives in Russia... her brother lives in France.", "", "", "", "; semi-colon",""));
        questionList.add(new Question("I found Sara...s shirt on the chair.", "", "", "", "' an apostrophe",""));
        questionList.add(new Question("What time is it ___", "", "", "", "?",""));
        questionList.add(new Question("Tommy has two sisters ___", "", "", "", ".",""));
        questionList.add(new Question("Finish your plate ___", "", "", "", ".",""));
        questionList.add(new Question("Wow, they are already done ___", "", "", "", "!",""));
        questionList.add(new Question("The cat watches the mouse ___", "", "", "", ".",""));
        questionList.add(new Question("Is there another person coming", "", "", "", "?",""));
        questionList.add(new Question("Careful, it is hot ___", "", "", "", "!",""));
        questionList.add(new Question("Give me the red pencil", "", "", "", ".",""));
        questionList.add(new Question("Make your bed before coming downstairs", "", "", "", ".",""));
        questionList.add(new Question("Did I give you a key ", "", "", "", "?",""));
        questionList.add(new Question("This is so beautiful", "", "", "", "!",""));
        questionList.add(new Question("Mark and Josh go to the park", "", "", "", ".",""));
        questionList.add(new Question("When is grandma arriving", "", "", "", "?",""));
        questionList.add(new Question("The teacher is writing on the board", "", "", "", ".",""));
        questionList.add(new Question("I like this shirt so much", "", "", "", "!",""));
        questionList.add(new Question("Place the cap on the bottle", "", "", "", ".",""));
        questionList.add(new Question("I feel good today ___", "", "", "", ".",""));
        questionList.add(new Question("Can you hear me ___", "", "", "", "?",""));
        questionList.add(new Question("I like oranges ___", "", "", "", ".",""));
        questionList.add(new Question("What time did you go to the movie last night ___", "", "", "", "?",""));
        questionList.add(new Question("Where are we going  ___", "", "", "", "?",""));
        questionList.add(new Question("I wonder how old he is ___", "", "", "", ".",""));
        questionList.add(new Question("Hey everybody, look at me ___", "", "", "", "!",""));
        questionList.add(new Question("Doesn't anybody want to come with me ___", "", "", "", "?",""));
        questionList.add(new Question("I think we can go now", "", "", "", ".",""));
        questionList.add(new Question("I am so excited! Our team scored a point", "", "", "", "!",""));
        questionList.add(new Question("When are you going to take out the trash", "", "", "", "?",""));
        questionList.add(new Question("Hello, how are you ", "", "", "", "?",""));
        questionList.add(new Question("Didn't you go to the store yesterday", "", "", "", "?",""));
        questionList.add(new Question("I think it's supposed to snow tomorrow", "", "", "", ".",""));
        questionList.add(new Question("Yay! I am finished with the quiz", "", "", "", "!",""));
        questionList.add(new Question("Where do you live Mr. Ali", "", "", "", "?",""));
        questionList.add(new Question("What a beautiful day", "", "", "", "!",""));
        questionList.add(new Question("The cheetah chased the deer_______", "", "", "", ".",""));
        questionList.add(new Question("You did a great job ______", "", "", "", "!",""));
        questionList.add(new Question("What day is it today_", "", "", "", "?",""));
        questionList.add(new Question("Which one of the following marks represents a question", "", "", "", "?",""));
        questionList.add(new Question("Which one of the following marks represents a full stop", "", "", "", ".",""));
        questionList.add(new Question("Which one of the following marks represents a comma:", "", "", "", ",",""));
        return questionList;
    }

    // method to return english pronoun question list
    private static ArrayList<Question> englishPronounQuestionList(){
        ArrayList<Question> questionList = new ArrayList<>();
        questionList.add(new Question("John is my student. ———————– is very intelligent.", "He", "She", "It", "He", ""));
        questionList.add(new Question("Alice is my sister. —————————- lives abroad.", "He", "She", "They", "She", ""));
        questionList.add(new Question("John and Mary are my students. ———————– are very hard working.", "They", "He", "She", "They", ""));
        questionList.add(new Question("My dog is smarter than ————————.", "Their", "Theirs", "Your", "Theirs", ""));
        questionList.add(new Question("This is ——————— dog.", "Mine", "My", "Ours", "My", ""));
        questionList.add(new Question("———————— is raining.", "They", "He", "It", "It", ""));
        questionList.add(new Question("Children went on a picnic. ———————– had a nice time.", "He", "She", "They", "They", ""));
        questionList.add(new Question("My parents live in a village. I visit ———————- often.", "Them", "We", "Us", "Them", ""));
        questionList.add(new Question("His children are very hard working. ———————— is very proud of them.", "They", "He", "She", "He", ""));
        questionList.add(new Question("I have invited all of my friends and ———————- have all agreed to come.", "They", "He", "She", "They", ""));
        questionList.add(new Question("The apple was overripe. We threw ———————– away.", "Them", "This", "It", "It", ""));
        questionList.add(new Question("My car is better than ———————–.", "Yours", "Your", "Her", "Yours", ""));
        questionList.add(new Question("Her hair is black. ——————— has turned grey.", "Mine", "My", "I", "Mine", ""));
        questionList.add(new Question("I have lost my keys. Did you see ———————-?", "They", "That", "Them", "Them", ""));
        questionList.add(new Question("We bought some apples. ————————- were very sweet.", "They", "We", "I", "They", ""));
        questionList.add(new Question("Give that to ____.", "me", "I", "We", "me", ""));
        questionList.add(new Question("Did she see ___?", "We", "I", "us", "us", ""));
        questionList.add(new Question("Did you phone ____?", "She", "her", "herself", "her", ""));
        questionList.add(new Question("I took it from ____.", "them", "they", "her", "them", ""));
        questionList.add(new Question("It's not up to ____.", "we", "she", "us", "us", ""));
        questionList.add(new Question("My sister and ____ went there.", "I", "me", "us", "I", ""));
        questionList.add(new Question("Between you and ____, I think it's a stupid idea", "I", "we", "me", "me", ""));
        questionList.add(new Question("____ is the white one.", "Mine", "My", "Her", "Mine", ""));
        questionList.add(new Question("What did ____ say about it?", "He", "She", "They", "They", ""));
        questionList.add(new Question("They said ____ had to pay for it.", "they", "us", "we", "we", ""));
        questionList.add(new Question("I told ____ to be here at three o'clock.", "he", "him", "they", "him", ""));
        questionList.add(new Question("What did ____ want?", "she", "he", "her", "she", ""));
        questionList.add(new Question("Tell ____ what happened.", "I", "me", "them", "me", ""));
        questionList.add(new Question("If ____ have time, it should be OK.", "us", "we", "she", "we", ""));
        questionList.add(new Question("It's got nothing to do with ____.", "you and me", "you and I", "you and her", "you and me", ""));
        questionList.add(new Question("I took ____ both.", "It", "Its", "them", "them", ""));
        questionList.add(new Question("That's ____ place.", "my", "mine", "our", "my", ""));
        questionList.add(new Question("Did ____ friends arrive on time?", "your", "yours", "our", "your", ""));
        questionList.add(new Question("We had the time of ____ lives.", "ours", "our", "her", "our", ""));
        questionList.add(new Question("That's ____.", "mine", "my", "her", "mine", ""));
        questionList.add(new Question("Have you seen ____ things?", "their", "theirs", "her", "their", ""));
        questionList.add(new Question("The cat drank ____ milk.", "its", "it's", "her", "its", ""));
        questionList.add(new Question("She's a friend of ____.", "our", "ours", "her", "ours", ""));
        questionList.add(new Question("I did it on ____ own.", "my", "mine", "her", "my", ""));
        questionList.add(new Question("Is this ____?", "your", "yours", "her", "yours", ""));
        questionList.add(new Question("Are these ____?", "your", "yours", "her", "yours", ""));
        questionList.add(new Question("Explain it again _____, please.", "to us", "us", "her", "to us", ""));
        questionList.add(new Question("She sent a letter _____.", "them", "to them", "to us", "to them", ""));
        questionList.add(new Question("He told a joke _____.", "to them", "them", "her", "to them", ""));
        questionList.add(new Question("He sent ____ a letter.", "me", "to me", "him", "me", ""));
        questionList.add(new Question("He warned ____ about it.", "us", "to us", "her", "us", ""));
        questionList.add(new Question("Post it _____ as soon as you can, please.", "me", "to me", "to us", "to me", ""));
        questionList.add(new Question("Ayed recommended it ____.", "me", "to me", "to us", "to me", ""));
        questionList.add(new Question("He wrote _____ a very rude letter.", "me", "to me", "us", "me", ""));
        questionList.add(new Question("She wrote a nice letter_____.", "me", "to me", "her", "to me", ""));
        questionList.add(new Question("Listen ____.", "to me", "me", "him", "to me", ""));
        questionList.add(new Question("She advised _____ not to go there.", "us", "to us", "her", "us", ""));
        questionList.add(new Question("She spoke ____ as soon as we arrived.", "us", "to us", "her", "to us", ""));
        questionList.add(new Question("He explained ____ the problem.", "us", "to us", "him", "to us", ""));
        questionList.add(new Question("He told ____ a lie.", "me", "to me", "her", "me", ""));
        questionList.add(new Question("I recommended ____ to do it as soon as possible.", "him", "to him", "to us", "to him", ""));
        questionList.add(new Question("They granted ____ an extension for submitting his work.", "him", "to him", "to us", "him", ""));
        questionList.add(new Question("It belongs to ____.", "him", "his", "her", "him", ""));
        questionList.add(new Question("Is that ____ case?", "your", "yours", "ours", "your", ""));
        questionList.add(new Question("____ mother is coming to collect them.", "Theirs", "Their", "there", "Their", ""));
        questionList.add(new Question("It's ____.", "our", "ours", "your", "ours", ""));
        questionList.add(new Question("____ is red.", "Ours", "Our", "your", "Ours", ""));
        questionList.add(new Question("____ car is over there.", "ours", "ours", "her", "our", ""));
        questionList.add(new Question("Is it ____ or his?", "yours", "your", "our", "yours", ""));
        questionList.add(new Question("____ plan is very different.", "Their", "There", "Theirs", "Their", ""));
        questionList.add(new Question("I took her book by mistake, but who took ____?", "my", "mine", "both are correct", "mine", ""));
        questionList.add(new Question("Every dog has ____ day.", "its", "it's", "it", "its", ""));
        questionList.add(new Question("Is ____ a bank near here?", "it", "their", "there", "there", ""));
        questionList.add(new Question("____ was a lot of rain yesterday.", "It", "There", "Their", "There", ""));
        questionList.add(new Question("____ rained a lot yesterday.", "It", "There", "Their", "It", ""));
        questionList.add(new Question("How much time is ____ left?", "it", "there", "their", "there", ""));
        questionList.add(new Question("____ were too many people there.", "They", "There", "Their", "There", ""));
        questionList.add(new Question("____ is a very big station, so make sure you arrive on time.", "It", "They", "There", "It", ""));
        questionList.add(new Question("____ is very complicated.", "It", "There", "Their", "It", ""));
        questionList.add(new Question("Is ____ anything in the bag?", "it", "there", "their", "there", ""));
        questionList.add(new Question("Is ____ a good movie on TV tonight?", "there", "it", "their", "it", ""));
        questionList.add(new Question("Was ____ much traffic this morning?", "it", "there", "their", "there", ""));
        questionList.add(new Question("She wrote a nice letter_____.", "me", "to me", "her", "to me", ""));
        questionList.add(new Question("Explain it again _____, please.", "to us", "us", "her", "to us", ""));
        questionList.add(new Question("This is ——————— dog.", "my", "mine", "her", "my", ""));
        return questionList;
    }

    // method to return english preposition question list
    private static ArrayList<Question> englishPrepositionList(){
        ArrayList<Question> questionList = new ArrayList<>();
        questionList.add(new Question("My birthday's ...... May", "in", "on", "at", "in", ""));
        questionList.add(new Question("She'll be away ...... next week", "since", "at", "until", "until", ""));
        questionList.add(new Question("The exam is ...... the tenth of December", "since", "at", "on", "on", ""));
        questionList.add(new Question("I always have dinner with my family ..... Christmas Day", "in", "at", "on", "on", ""));
        questionList.add(new Question("In Spain, they give each other presents ..... Christmas Eve", "in", "on", "at", "on", ""));
        questionList.add(new Question("The lecture finished ..... five thirty", "at", "on", "in", "at", ""));
        questionList.add(new Question("I hate it when people telephone ......... I'm having dinner", "during", "while", "for", "while", ""));
        questionList.add(new Question("I like to go to a party ....... New Year's Eve", "in", "on", "at", "on", ""));
        questionList.add(new Question("The term is from September ...... December", "at", "for", "to", "to", ""));
        questionList.add(new Question("He hasn't worked ....... he lost his job", "since", "for", "by", "since", ""));
        questionList.add(new Question("The car won't be ready ..... Friday", "until", "in", "since", "until", ""));
        questionList.add(new Question("You must see Paris ..... the Spring", "in", "on", "at", "in", ""));
        questionList.add(new Question("He doesn't start work until late .... the afternoon", "on", "in", "at", "in", ""));
        questionList.add(new Question("Snow generally falls ..... February", "in", "on", "at", "in", ""));
        questionList.add(new Question("People give chocolate eggs as presents ...... Easter", "on", "in", "at", "at", ""));
        questionList.add(new Question("Did I miss anything ........ I was on the phone?", "while", "during", "for", "while", ""));
        questionList.add(new Question("I have lessons .... Mondays and Wednesdays", "in", "on", "at", "on", ""));
        questionList.add(new Question("He didn't do the work ...... his boss got angry", "since", "for", "until", "until", ""));
        questionList.add(new Question("She was off work ...... a fortnight", "for", "at", "in", "for", ""));
        questionList.add(new Question("Nobody spoke ...... the film", "during", "since", "on", "during", ""));
        questionList.add(new Question("It's always colder ....... November than September", "on", "in", "at", "in", ""));
        questionList.add(new Question("Their first child was born ..... the spring", "on", "at", "in", "in", ""));
        questionList.add(new Question("I've known him ....... a long time", "since", "for", "at", "for", ""));
        questionList.add(new Question("People celebrate Guy Fawkes' Night ..... the fifth of November", "on", "in", "at", "on", ""));
        questionList.add(new Question("They'll deliver .......... two weeks", "at", "within", "by", "within", ""));
        questionList.add(new Question("I'll see you ..... ten o' clock", "at", "on", "in", "at", ""));
        questionList.add(new Question("She died ..... 1993", "on", "in", "at", "in", ""));
        questionList.add(new Question("We made lots of friends .......... we were in Mexico", "during", "while", "since", "while", ""));
        questionList.add(new Question("It gets very cold ..... winter", "on", "at", "in", "in", ""));
        questionList.add(new Question("She was born ..... 1985", "at", "on", "in", "in", ""));
        questionList.add(new Question("In England they say .... the weekend", "on", "at", "in", "at", ""));
        questionList.add(new Question("In America they say..... the weekend", "at", "on", "in", "on", ""));
        questionList.add(new Question("Her birthday's ..... June", "in", "on", "at", "in", ""));
        questionList.add(new Question("I'll be seeing them ...... a month's time", "on", "in", "at", "in", ""));
        questionList.add(new Question("I leave home very early ..... the morning", "on", "at", "in", "in", ""));
        questionList.add(new Question("We left ..... Monday", "at", "on", "for", "on", ""));
        questionList.add(new Question("He's been with the company ........ the summer", "since", "for", "at", "since", ""));
        questionList.add(new Question("She's going on holiday ...... Xmas", "in", "at", "at", "at", ""));
        questionList.add(new Question("The Black Death occurred ..... the Middle Ages", "in", "on", "at", "in", ""));
        questionList.add(new Question("I'll be working ...... the summer holidays", "on", "during", "while", "during", ""));
        questionList.add(new Question("Leaves fall ..... Autumn", "on", "at", "in", "in", ""));
        questionList.add(new Question("She was Prime Minister ....... ten years", "since", "for", "at", "for", ""));
        questionList.add(new Question("The law was changed ..... the nineteenth century", "in", "on", "at", "in", ""));
        questionList.add(new Question("He'll be here ..... a moment", "in", "on", "at", "in", ""));
        questionList.add(new Question("Term finishes ..... a Thursday for some reason", "at", "in", "on", "on", ""));
        questionList.add(new Question("Their wedding is .... the eleventh of July", "in", "on", "at", "on", ""));
        questionList.add(new Question("I worked there ....... five years", "since", "for", "in", "for", ""));
        questionList.add(new Question("I haven't seen her ........ April", "since", "for", "during", "since", ""));
        questionList.add(new Question("The film starts ........ eight o' clock", "in", "on", "at", "at", ""));
        questionList.add(new Question("Mayday is celebrated .... May the first", "in", "on", "at", "on", ""));
        questionList.add(new Question("Please keep quiet ......... the performance", "during", "by", "in", "during", ""));
        questionList.add(new Question("The contract is from July ...... December", "at", "for", "until", "until", ""));
        questionList.add(new Question("The film will be ready ..... two hours", "for", "at", "in", "in", ""));
        questionList.add(new Question("The plane left ....... time", "on", "at", "to", "on", ""));
        questionList.add(new Question("I began to feel ill ....... the film", "while", "for", "during", "during", ""));
        questionList.add(new Question("The play starts ..... half past seven", "at", "on", "in", "at", ""));
        questionList.add(new Question("The strike started .... the fifteenth of May", "in", "on", "at", "on", ""));
        questionList.add(new Question("More people have heart attacks ..... Monday morning than at any other time", "on", "in", "at", "on", ""));
        questionList.add(new Question("She got pregnant ....... eighteen", "in", "on", "at", "at", ""));
        questionList.add(new Question("The results come out .... July", "on", "in", "at", "in", ""));
        questionList.add(new Question("There is a public holiday ........ May the first", "on", "in", "at", "on", ""));
        questionList.add(new Question("I haven't seen her ..... the last meeting", "for", "since", "by", "since", ""));
        questionList.add(new Question("She was born ..... Christmas Eve", "on", "at", "in", "on", ""));
        questionList.add(new Question("The flower blossoms .... early April", "on", "at", "in", "in", ""));
        questionList.add(new Question("I didn't have a chance to speak ......... the meeting", "during", "for", "while", "during", ""));
        questionList.add(new Question("Traffic is terrible .... rush hour", "in", "while", "until", "in", ""));
        questionList.add(new Question("She left her job ....... August", "in", "on", "at", "in", ""));
        questionList.add(new Question("Her birthday is ..... a Tuesday this year", "on", "at", "in", "on", ""));
        questionList.add(new Question("We met ...... a foggy day in March", "on", "at", "in", "on", ""));
        questionList.add(new Question("Their car was broken into ..... Saturday night", "in", "at", "on", "on", ""));
        questionList.add(new Question("He worked there ...... two years", "in", "on", "at", "in", ""));
        questionList.add(new Question("They're leaving ...... June", "on", "in", "at", "in", ""));
        questionList.add(new Question("I was ill ...... a week", "since", "while", "for", "for", ""));
        questionList.add(new Question("I worked there ...... July till September", "in", "to", "from", "from", ""));
        questionList.add(new Question("He was born ..... 1968", "in", "on", "at", "in", ""));
        return questionList;
    }

    // ----------> URDU

    // return question list according to category
    public static List<Question> getQuestions(String quizCategory){
        if (quizCategory.equals("math1")){
            return mathAdditionQuestionList();
        }
        else if (quizCategory.equals("math2")){
            return mathSubtractionQuestionList();
        }
        else if (quizCategory.equals("math3")){
            return mathMultiplicationQuestionList();
        }
        else if (quizCategory.equals("math4")){
            return mathDivisionQuestionList();
        }
        else if (quizCategory.equals("english1")){
            return englishIsAmAreQuestionList();
        }
        else if (quizCategory.equals("english2")){
            return englishPunctuationList();
        }
        else if (quizCategory.equals("english3")){
            return englishPronounQuestionList();
        }
        else {
            return englishPronounQuestionList();
        }
//        else if (quizCategory.equals("english4")){
//            return englishPrepositionList();
//        }
    }
}
